spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/blackjack}

  r2dbc:
    url: ${SPRING_R2DBMS_URL:r2dbc:mysql://localhost:3306/blackjack}
    username: ${SPRING_R2DBC_USERNAME:blackjack}
    password: ${SPRING_R2DBC_PASSWORD:blackjack}

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.data.mongodb: DEBUG